// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU1Rd-D_fOHjjkVkHJ2DjP7XpgkVglL1E',
    appId: '1:792850201769:web:61bbb57c49e27d12ab3db8',
    messagingSenderId: '792850201769',
    projectId: 'mystery-habit',
    authDomain: 'mystery-habit.firebaseapp.com',
    storageBucket: 'mystery-habit.firebasestorage.app',
    measurementId: 'G-W7NEFGQJZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbavR-QrSR6L4gB7quFSB3Ameh7C_nWpE',
    appId: '1:792850201769:android:cd7acb13409c34d0ab3db8',
    messagingSenderId: '792850201769',
    projectId: 'mystery-habit',
    storageBucket: 'mystery-habit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYrtnk1u9v1nyv_Db1TvTWQ6c_Iej6vH8',
    appId: '1:792850201769:ios:2cd27ca21fb4cb30ab3db8',
    messagingSenderId: '792850201769',
    projectId: 'mystery-habit',
    storageBucket: 'mystery-habit.firebasestorage.app',
    iosBundleId: 'com.aquaterralife.mysteryHabit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYrtnk1u9v1nyv_Db1TvTWQ6c_Iej6vH8',
    appId: '1:792850201769:ios:2cd27ca21fb4cb30ab3db8',
    messagingSenderId: '792850201769',
    projectId: 'mystery-habit',
    storageBucket: 'mystery-habit.firebasestorage.app',
    iosBundleId: 'com.aquaterralife.mysteryHabit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU1Rd-D_fOHjjkVkHJ2DjP7XpgkVglL1E',
    appId: '1:792850201769:web:e483ef9d74521b6aab3db8',
    messagingSenderId: '792850201769',
    projectId: 'mystery-habit',
    authDomain: 'mystery-habit.firebaseapp.com',
    storageBucket: 'mystery-habit.firebasestorage.app',
    measurementId: 'G-YV7ZCEFQVV',
  );
}
